// Team 9 Hayden Trent, Liang Wenxuan, Jack Lu
// EECE2140
// basic enum class 'inspiration'/basic logic provided by Stack Overflow https://stackoverflow.com/questions/59426711/c-class-traffic-light-with-enum
// Print statement structure provided by OpenAI codex
// Comments explaining code generated by OpenAI codex.
//

#include <iostream>   // for input and output
                     // 用于输入和输出
#include <string>     // for string
                     // 用于字符串
#include <thread>     // for sleep
                     // 用于暂停程序
#include <chrono>     // for time
                     // 用于时间计算
#include <limits>     // for input cleanup
                     // 用于清理输入

using namespace std;

// This enum stores the possible car light states
// 这个枚举保存汽车信号灯的所有可能状态
enum class CarSignal {
    Red,
    Yellow,
    Green,
    RedArrow,
    YellowArrow,
    GreenArrow
};

// This enum stores the possible pedestrian light states
// 这个枚举保存行人信号灯的所有可能状态
enum class PedSignal {
    DontWalk,
    Walk,
    FlashingDontWalk
};

// This enum stores the order of phases in the intersection cycle
// 这个枚举保存十字路口信号灯循环的阶段顺序
enum class Phase {
    NS_Left_Green,     // north-south left turn green
                       // 南北左转绿灯
    NS_Left_Yellow,    // north-south left turn yellow
                       // 南北左转黄灯
    NS_Left_AllRed,    // all red before next phase
                       // 下一阶段前全红
    NS_Through_Green,  // north-south straight green
                       // 南北直行绿灯
    NS_Through_Yellow, // north-south straight yellow
                       // 南北直行黄灯
    AllRed_To_EW,      // all red before east-west starts
                       // 东西方向开始前全红
    EW_Left_Green,     // east-west left turn green
                       // 东西左转绿灯
    EW_Left_Yellow,    // east-west left turn yellow
                       // 东西左转黄灯
    EW_Left_AllRed,    // all red before next phase
                       // 下一阶段前全红
    EW_Through_Green,  // east-west straight green
                       // 东西直行绿灯
    EW_Through_Yellow, // east-west straight yellow
                       // 东西直行黄灯
    AllRed_To_NS       // all red before north-south starts again
                       // 南北方向再次开始前全红
};

// This struct stores all light outputs at one moment
// 这个结构体保存某一时刻所有灯的状态
struct IntersectionState {
    CarSignal nsThrough; // north-south straight light
                         // 南北直行灯
    CarSignal nsLeft;    // north-south left turn light
                         // 南北左转灯
    CarSignal ewThrough; // east-west straight light
                         // 东西直行灯
    CarSignal ewLeft;    // east-west left turn light
                         // 东西左转灯
    PedSignal nsPed;     // pedestrian light crossing north-south road
                         // 过南北道路的行人灯
    PedSignal ewPed;     // pedestrian light crossing east-west road
                         // 过东西道路的行人灯
};

class IntersectionController {
private:
    // current phase of the traffic light cycle
    // 当前信号灯循环阶段
    Phase currentPhase = Phase::NS_Left_Green;

    // how long we have been in the current phase
    // 当前阶段已经过去的时间
    double timeInPhase = 0.0;

    // timer values for each type of phase
    // 每一种阶段的时间设置
    double leftGreenTime = 4.0;
    double leftYellowTime = 2.0;
    double throughGreenTime = 8.0;
    double yellowTime = 3.0;
    double allRedTime = 1.0;
    double walkTime = 5.0;
    double flashTime = 3.0;

    // move to a new phase and reset the phase timer
    // 进入新的阶段，并把阶段时间清零
    void changePhase(Phase next) {
        currentPhase = next;
        timeInPhase = 0.0;
    }

    // decide what pedestrian signal to show
    // first Walk, then FlashingDontWalk, then DontWalk
    // 决定行人灯显示什么
    // 先是 Walk，然后是 FlashingDontWalk，最后是 DontWalk
    PedSignal pedDisplay() const {
        if (timeInPhase < walkTime) {
            return PedSignal::Walk;
        }
        if (timeInPhase < walkTime + flashTime) {
            return PedSignal::FlashingDontWalk;
        }
        return PedSignal::DontWalk;
    }

    // ask the user for a positive integer
    // keep asking until the user enters good input
    // 让用户输入一个正整数
    // 如果输入错误，就一直重新输入
    int getValidIntInput(const string& prompt) {
        int value;

        while (true) {
            cout << prompt;
            cin >> value;

            // if input fails or number is not positive, ask again
            // 如果输入失败，或者数字不是正数，就重新输入
            if (cin.fail() || value <= 0) {
                cin.clear(); // clear error state
                             // 清除输入错误状态
                cin.ignore(numeric_limits<streamsize>::max(), '\n'); // remove bad input
                                                                      // 删除错误输入
                cout << "Invalid input. Enter a positive integer.\n";
            } else {
                cin.ignore(numeric_limits<streamsize>::max(), '\n'); // remove extra input
                                                                      // 删除多余输入
                return value;
            }
        }
    }

public:
    void inputTimers();
    void update(double time);
    IntersectionState getState() const;
    Phase getCurrentPhase() const;
};

// Ask the user to enter all timer values
// 让用户输入所有时间设置
void IntersectionController::inputTimers() {
    leftGreenTime = getValidIntInput("Enter left green time: ");
    leftYellowTime = getValidIntInput("Enter left yellow time: ");
    throughGreenTime = getValidIntInput("Enter through green time: ");
    yellowTime = getValidIntInput("Enter through yellow time: ");
    allRedTime = getValidIntInput("Enter all-red time: ");
    walkTime = getValidIntInput("Enter walk time: ");
    flashTime = getValidIntInput("Enter flashing don't walk time: ");
}

// Update the controller by adding elapsed time
// When time in the current phase is long enough, move to next phase
// this is the actual controlling logic of the phases -- Hayden
// 把经过的时间加到控制器里
// 当当前阶段时间够长时，进入下一个阶段
// 这是阶段控制的主要逻辑 -- Hayden
void IntersectionController::update(double time) {
    timeInPhase += time;

    switch (currentPhase) {
    case Phase::NS_Left_Green:
        if (timeInPhase >= leftGreenTime) {
            changePhase(Phase::NS_Left_Yellow);
        }
        break;

    case Phase::NS_Left_Yellow:
        if (timeInPhase >= leftYellowTime) {
            changePhase(Phase::NS_Left_AllRed);
        }
        break;

    case Phase::NS_Left_AllRed:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::NS_Through_Green);
        }
        break;

    case Phase::NS_Through_Green:
        if (timeInPhase >= throughGreenTime) {
            changePhase(Phase::NS_Through_Yellow);
        }
        break;

    case Phase::NS_Through_Yellow:
        if (timeInPhase >= yellowTime) {
            changePhase(Phase::AllRed_To_EW);
        }
        break;

    case Phase::AllRed_To_EW:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::EW_Left_Green);
        }
        break;

    case Phase::EW_Left_Green:
        if (timeInPhase >= leftGreenTime) {
            changePhase(Phase::EW_Left_Yellow);
        }
        break;

    case Phase::EW_Left_Yellow:
        if (timeInPhase >= leftYellowTime) {
            changePhase(Phase::EW_Left_AllRed);
        }
        break;

    case Phase::EW_Left_AllRed:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::EW_Through_Green);
        }
        break;

    case Phase::EW_Through_Green:
        if (timeInPhase >= throughGreenTime) {
            changePhase(Phase::EW_Through_Yellow);
        }
        break;

    case Phase::EW_Through_Yellow:
        if (timeInPhase >= yellowTime) {
            changePhase(Phase::AllRed_To_NS);
        }
        break;

    case Phase::AllRed_To_NS:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::NS_Left_Green);
        }
        break;
    }
}

// Return the current full light state for cars and pedestrians
// Here is the 'getter' for the case's phase -- Hayden
// 返回当前汽车灯和行人灯的完整状态
// 这是取得当前阶段状态的函数 -- Hayden
IntersectionState IntersectionController::getState() const {
    switch (currentPhase) {
    case Phase::NS_Left_Green:
        return {
            CarSignal::Red,         // NS straight is red
                                    // 南北直行是红灯
            CarSignal::GreenArrow,  // NS left is green arrow
                                    // 南北左转是绿箭头
            CarSignal::Red,         // EW straight is red
                                    // 东西直行是红灯
            CarSignal::RedArrow,    // EW left is red arrow
                                    // 东西左转是红箭头
            PedSignal::DontWalk,    // NS pedestrian stops
                                    // 南北行人停止
            PedSignal::DontWalk     // EW pedestrian stops
                                    // 东西行人停止
        };

    case Phase::NS_Left_Yellow:
        return {
            CarSignal::Red,
            CarSignal::YellowArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::NS_Left_AllRed:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::NS_Through_Green:
        return {
            CarSignal::Green,       // NS straight can go
                                    // 南北直行可以走
            CarSignal::RedArrow,    // NS left must stop
                                    // 南北左转必须停
            CarSignal::Red,         // EW straight must stop
                                    // 东西直行必须停
            CarSignal::RedArrow,    // EW left must stop
                                    // 东西左转必须停
            PedSignal::DontWalk,    // NS pedestrian stops
                                    // 南北行人停止
            pedDisplay()            // EW pedestrian may walk
                                    // 东西行人可以通行
        };

    case Phase::NS_Through_Yellow:
        return {
            CarSignal::Yellow,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::AllRed_To_EW:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Left_Green:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::GreenArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Left_Yellow:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::YellowArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Left_AllRed:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Through_Green:
        return {
            CarSignal::Red,         // NS straight must stop
                                    // 南北直行必须停
            CarSignal::RedArrow,    // NS left must stop
                                    // 南北左转必须停
            CarSignal::Green,       // EW straight can go
                                    // 东西直行可以走
            CarSignal::RedArrow,    // EW left must stop
                                    // 东西左转必须停
            pedDisplay(),           // NS pedestrian may walk
                                    // 南北行人可以通行
            PedSignal::DontWalk     // EW pedestrian stops
                                    // 东西行人停止
        };

    case Phase::EW_Through_Yellow:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Yellow,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::AllRed_To_NS:
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };
    }

    // fallback return
    // 备用返回值
    return {
        CarSignal::Red,
        CarSignal::RedArrow,
        CarSignal::Red,
        CarSignal::RedArrow,
        PedSignal::DontWalk,
        PedSignal::DontWalk
    };
}

// Return the current phase
// 返回当前阶段
Phase IntersectionController::getCurrentPhase() const {
    return currentPhase;
}

// Change car signal enum into readable text
// 把汽车信号灯枚举转换成可读文字
string toString(CarSignal s) {
    switch (s) {
    case CarSignal::Red: return "Red";
    case CarSignal::Yellow: return "Yellow";
    case CarSignal::Green: return "Green";
    case CarSignal::RedArrow: return "RedArrow";
    case CarSignal::YellowArrow: return "YellowArrow";
    case CarSignal::GreenArrow: return "GreenArrow";
    }
    return "";
}

// Change pedestrian signal enum into readable text
// 把行人信号灯枚举转换成可读文字
string toString(PedSignal s) {
    switch (s) {
    case PedSignal::DontWalk: return "DontWalk";
    case PedSignal::Walk: return "Walk";
    case PedSignal::FlashingDontWalk: return "FlashingDontWalk";
    }
    return "";
}

// Print the full state of the intersection
// 打印十字路口当前的完整状态
void printState(const IntersectionState& s) {
    cout << "NS Through: " << toString(s.nsThrough) << "\n";
    cout << "NS Left   : " << toString(s.nsLeft) << "\n";
    cout << "EW Through: " << toString(s.ewThrough) << "\n";
    cout << "EW Left   : " << toString(s.ewLeft) << "\n";
    cout << "NS Ped    : " << toString(s.nsPed) << "\n";
    cout << "EW Ped    : " << toString(s.ewPed) << "\n";
    cout << "--------------------------\n";
}

int main() {
    // Create the controller object
    // 创建控制器对象
    IntersectionController controller;

    // Ask the user for timer values
    // 让用户输入时间设置
    controller.inputTimers();

    // Save the start time
    // 保存开始时间
    auto lastTime = chrono::steady_clock::now();

    // Save the first phase so we know when it changes
    // 保存最开始的阶段，这样我们可以知道什么时候阶段改变
    Phase lastPrintedPhase = controller.getCurrentPhase();

    // Print the starting light state
    // 打印开始时的灯状态
    printState(controller.getState());

    // Keep running forever
    // 一直循环运行
    while (true) {
        // Get current time
        // 获取当前时间
        auto currentTime = chrono::steady_clock::now();

        // Find how much time passed since last loop
        // 计算距离上一次循环过去了多少时间
        chrono::duration<double> elapsed = currentTime - lastTime;
        lastTime = currentTime;

        // Update the traffic light system
        // 更新交通灯系统
        controller.update(elapsed.count());

        // Only print when the phase changes
        // 只有阶段改变时才打印
        if (controller.getCurrentPhase() != lastPrintedPhase) {
            lastPrintedPhase = controller.getCurrentPhase();
            printState(controller.getState());
        }

        // Sleep a little so the loop does not run too fast
        // 暂停一点时间，避免循环运行太快
        this_thread::sleep_for(chrono::milliseconds(50));
    }

    return 0;
}
