// Team 9 Hayden Trent, Liang Wenxuan, Jack Lu
// EECE2140
// basic enum class 'inspiration'/basic logic provided by Stack Overflow https://stackoverflow.com/questions/59426711/c-class-traffic-light-with-enum
// Print statement structure provided by OpenAI codex
// Comments explaining code generated by OpenAI codex + CoPilot and proofread/edited by Hayden Trent.
//Translation to Chinese provided by OpenAI codex and Co-Pilot to reduce potential language barrier.
//

#include <iostream>
#include <string>
#include <thread>
#include <chrono>
#include <limits>

using namespace std;

// This enum stores the possible car light states
//enums used in order to be compatible with switch statements
// 这个枚举保存汽车信号灯的所有可能状态
enum class CarSignal {
    Red,
    Yellow,
    Green,
    RedArrow,
    YellowArrow,
    GreenArrow,
    FlashingRed,
    FlashingRedArrow
};

// This enum stores the possible pedestrian light states
// 这个枚举保存行人信号灯的所有可能状态
enum class PedSignal {
    DontWalk,
    Walk,
    FlashingDontWalk,
    Flashing
};

// This enum stores the order of phases in the intersection cycle
// 这个枚举保存十字路口信号灯循环的阶段顺序
enum class Phase {
    NS_Left_Green,     // north-south left turn green
                       // 南北左转绿灯
    NS_Left_Yellow,    // north-south left turn yellow
                       // 南北左转黄灯
    NS_Left_AllRed,    // all red before next phase
                       // 下一阶段前全红
    NS_Through_Green,  // north-south straight green
                       // 南北直行绿灯
    NS_Through_Yellow, // north-south straight yellow
                       // 南北直行黄灯
    AllRed_To_EW,      // all red before east-west starts
                       // 东西方向开始前全红
    EW_Left_Green,     // east-west left turn green
                       // 东西左转绿灯
    EW_Left_Yellow,    // east-west left turn yellow
                       // 东西左转黄灯
    EW_Left_AllRed,    // all red before next phase
                       // 下一阶段前全红
    EW_Through_Green,  // east-west straight green
                       // 东西直行绿灯
    EW_Through_Yellow, // east-west straight yellow
                       // 东西直行黄灯
    AllRed_To_NS       // all red before north-south starts again
                       // 南北方向再次开始前全红
};

// This struct stores all light outputs at one moment, this struct declares the specific variables of from the previous Carsignal and PedSignal enums, and is used to return the full state of the intersection at once in the getState() function of the controller.
// 这个结构体保存某一时刻所有灯的状态，这个结构体声明了之前CarSignal和PedSignal枚举中的具体变量，并且在控制器的getState()函数中用来一次性返回十字路口的完整状态。
//this struct essentially declares that these variables must be given for every intersection state called later
//这个结构体基本上声明了每个十字路口状态都必须给出这些变量
struct IntersectionState {
    CarSignal nsThrough; // north-south straight light
                         // 南北直行灯
    CarSignal nsLeft;    // north-south left turn light
                         // 南北左转灯
    CarSignal ewThrough; // east-west straight light
                         // 东西直行灯
    CarSignal ewLeft;    // east-west left turn light
                         // 东西左转灯
    PedSignal nsPed;     // pedestrian light crossing north-south road
                         // 过南北道路的行人灯
    PedSignal ewPed;     // pedestrian light crossing east-west road
                         // 过东西道路的行人灯
};

class IntersectionController {
private:
    // current phase of the traffic light cycle, setting the default to NS_Left_Green, but it will change as the program runs.
    // 交通灯循环的当前阶段，默认设置为NS_Left_Green，但随着程序运行会改变
    Phase currentPhase = Phase::NS_Left_Green;

    // how long we have been in the current phase, used to check against the timer values to know when to change phase later.
    // 我们在当前阶段已经持续了多久，用来和时间设置比较，以便知道什么时候改变阶段。
    double timeInPhase = 0.0;

    // timer values for each type of phase
    // 每一种阶段的时间设置
    double leftGreenTime = 4.0;
    double leftYellowTime = 2.0;
    double throughGreenTime = 8.0;
    double yellowTime = 3.0;
    double allRedTime = 1.0;
    double walkTime = 5.0;
    double flashTime = 3.0;

    // move to a new phase and reset the phase timer, goes in order within the phase enum.
    // 转到一个新阶段并重置阶段计时器，按照阶段枚举中的顺序进行
    void changePhase(Phase next) {
        currentPhase = next;
        timeInPhase = 0.0;
    }

    // ask the user for a positive integer
    // keep asking until the user enters good input
    // 让用户输入一个正整数
    // 如果输入错误，就一直重新输入
    int getValidIntInput(const string& prompt) { // prompt is the text to show the user when asking for input, called by later functions.
                                                 // prompt是提示用户输入时显示的文本
        int value;

        while (true) {
            cout << prompt;
            cin >> value;

            // if input fails or number is not positive, ask again
            // 如果输入失败，或者数字不是正数，就重新输入
            if (cin.fail() || value <= 0) {
                cin.clear(); // clear error state
                             // 清除输入错误状态
                cin.ignore(numeric_limits<streamsize>::max(), '\n'); // remove bad input
                                                                      // 删除错误输入
                cout << "Invalid input. Enter a positive integer.\n";
            } else {
                cin.ignore(numeric_limits<streamsize>::max(), '\n'); // remove extra input
                                                                      // 删除多余输入
                return value;
            }
        }
    }

public: //declared public functions of the controller.
    void inputTimers();
    void update(double time);
    IntersectionState getState() const;
    Phase getCurrentPhase() const;
};

// Ask the user to enter all timer values
// 让用户输入所有时间设置
void IntersectionController::inputTimers() {
    leftGreenTime = getValidIntInput("Enter left green time: ");
    leftYellowTime = getValidIntInput("Enter left yellow time: ");
    throughGreenTime = getValidIntInput("Enter through green time: ");
    yellowTime = getValidIntInput("Enter through yellow time: ");
    allRedTime = getValidIntInput("Enter all-red time: ");
}

//This is what is used to tie the CarSignal enum and PedSignal enum to the Phase enum, this getState() function is declared as a struct object that can switch cases based on the phase enum, and returns a struct as well.
//这个函数用来把CarSignal枚举和PedSignal枚举和Phase枚举联系起来，这个getState()函数被声明为一个结构体，可以根据阶段枚举进行分情况讨论。
IntersectionState IntersectionController::getState() const {
    switch (currentPhase) {
    case Phase::NS_Left_Green: //traffic is going from NS to EW, so NS left is green, and EW through and left are red. Pedestrians can't walk.
        return {
            CarSignal::Red,
            CarSignal::GreenArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::NS_Left_Yellow: //same traffic as NS_Left_Green, but yellow instead of green. Pedestrians still can't walk.
        return {
            CarSignal::Red,
            CarSignal::YellowArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::NS_Left_AllRed: //all red for a moment before next phase, so all car signals are red. Pedestrians still can't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::NS_Through_Green: //traffic is going from NS to EW, so NS through is green, and EW through and left are red. Pedestrians crossing NS can walk.
        return {
            CarSignal::Green,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::Walk,
            PedSignal::DontWalk
        };

    case Phase::NS_Through_Yellow: //same traffic as NS_Through_Green, but yellow instead of green. Pedestrians crossing NS should see flashing don't walk.
        return {
            CarSignal::Yellow,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::FlashingDontWalk,
            PedSignal::DontWalk
        };

    case Phase::AllRed_To_EW: //all red for a moment before next phase, so all car signals are red. Pedestrians still can't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Left_Green: //   traffic is going from EW to NS, so EW left is green, and NS through and left are red. Pedestrians can't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::GreenArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Left_Yellow: //same traffic as EW_Left_Green, but yellow instead of green. Pedestrians still can't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::YellowArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Left_AllRed: //all red for a moment before next phase, so all car signals are red. Pedestrians still can't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };

    case Phase::EW_Through_Green: //traffic is going from EW to NS, so EW through is green, and NS through and left are red. Pedestrians crossing EW can walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Green,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::Walk
        };

    case Phase::EW_Through_Yellow: //same traffic as EW_Through_Green, but yellow instead of green. Pedestrians crossing EW should see flashing don't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Yellow,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::FlashingDontWalk
        };

    case Phase::AllRed_To_NS: //all red for a moment before next phase, so all car signals are red. Pedestrians still can't walk.
        return {
            CarSignal::Red,
            CarSignal::RedArrow,
            CarSignal::Red,
            CarSignal::RedArrow,
            PedSignal::DontWalk,
            PedSignal::DontWalk
        };
    }

    return { // default case should never be reached, but return all red and don't walk just in case, this is for emergencies.
             // 默认情况不应该被达到，但以防万一，返回全红和禁止行走
        CarSignal::FlashingRed,
        CarSignal::FlashingRedArrow,
        CarSignal::FlashingRed,
        CarSignal::FlashingRedArrow,
        PedSignal::Flashing,
        PedSignal::Flashing
    };
}


//this is the switch statement that receives the current phase, and then matches it to a case, if the case matches, and the time is up, it will call for a phase change and repeat this process as long as it is allowed to run.
//这是一个switch语句，接收当前阶段，然后匹配到一个case，如果时间到了，就会调用阶段改变，并且只要程序允许运行，就会一直重复这个过程。
void IntersectionController::update(double time) {
    timeInPhase += time;

    switch (currentPhase) {
    case Phase::NS_Left_Green:
        if (timeInPhase >= leftGreenTime) {
            changePhase(Phase::NS_Left_Yellow);
        }
        break;

    case Phase::NS_Left_Yellow:
        if (timeInPhase >= leftYellowTime) {
            changePhase(Phase::NS_Left_AllRed);
        }
        break;

    case Phase::NS_Left_AllRed:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::NS_Through_Green);
        }
        break;

    case Phase::NS_Through_Green:
        if (timeInPhase >= throughGreenTime) {
            changePhase(Phase::NS_Through_Yellow);
        }
        break;

    case Phase::NS_Through_Yellow:
        if (timeInPhase >= yellowTime) {
            changePhase(Phase::AllRed_To_EW);
        }
        break;

    case Phase::AllRed_To_EW:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::EW_Left_Green);
        }
        break;

    case Phase::EW_Left_Green:
        if (timeInPhase >= leftGreenTime) {
            changePhase(Phase::EW_Left_Yellow);
        }
        break;

    case Phase::EW_Left_Yellow:
        if (timeInPhase >= leftYellowTime) {
            changePhase(Phase::EW_Left_AllRed);
        }
        break;

    case Phase::EW_Left_AllRed:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::EW_Through_Green);
        }
        break;

    case Phase::EW_Through_Green:
        if (timeInPhase >= throughGreenTime) {
            changePhase(Phase::EW_Through_Yellow);
        }
        break;

    case Phase::EW_Through_Yellow:
        if (timeInPhase >= yellowTime) {
            changePhase(Phase::AllRed_To_NS);
        }
        break;

    case Phase::AllRed_To_NS:
        if (timeInPhase >= allRedTime) {
            changePhase(Phase::NS_Left_Green);
        }
        break;
    }
}




// Return the current phase
// 返回当前阶段
Phase IntersectionController::getCurrentPhase() const {
    return currentPhase;
}

// Change car signal enum into readable text, this is for terminal output and future UI display.
// 把汽车信号灯枚举转换成可读文字
string toString(CarSignal s) {
    switch (s) {
    case CarSignal::Red: return "Red";
    case CarSignal::Yellow: return "Yellow";
    case CarSignal::Green: return "Green";
    case CarSignal::RedArrow: return "RedArrow";
    case CarSignal::YellowArrow: return "YellowArrow";
    case CarSignal::GreenArrow: return "GreenArrow";
    case CarSignal::FlashingRed: return "FlashingRed";
    case CarSignal::FlashingRedArrow: return "FlashingRedArrow";

    }
    return "";
}

// Change pedestrian signal enum into readable text
// 把行人信号灯枚举转换成可读文字
string toString(PedSignal s) {
    switch (s) {
    case PedSignal::DontWalk: return "DontWalk";
    case PedSignal::Walk: return "Walk";
    case PedSignal::FlashingDontWalk: return "FlashingDontWalk";
    case PedSignal::Flashing: return "Flashing";

    }
    return "";
}

// Print the full state of the intersection
// 打印十字路口当前的完整状态
void printState(const IntersectionState& s) {
    cout << "NS Through: " << toString(s.nsThrough) << "\n"; // calls the toString function to convert the enum value into readable text, then prints it. This is done for all 6 signals in the intersection.
    cout << "NS Left   : " << toString(s.nsLeft) << "\n";
    cout << "EW Through: " << toString(s.ewThrough) << "\n";
    cout << "EW Left   : " << toString(s.ewLeft) << "\n";
    cout << "NS Ped    : " << toString(s.nsPed) << "\n";
    cout << "EW Ped    : " << toString(s.ewPed) << "\n";
    cout << "--------------------------\n";
}

int main() {
    // Create the controller object
    // 创建控制器对象
    IntersectionController controller;

    // Ask the user for timer values
    // 让用户输入时间设置
    controller.inputTimers();

    // Save the start time
    // 保存开始时间
    auto lastTime = chrono::steady_clock::now();

    // Save the first phase so we know when it changes
    // 保存最开始的阶段，这样我们可以知道什么时候阶段改变
    Phase lastPrintedPhase = controller.getCurrentPhase();

    // Print the starting light state
    // 打印开始时的灯状态
    printState(controller.getState());

    // Keep running forever
    // 一直循环运行
    while (true) {
        // Get current time
        // 获取当前时间
        auto currentTime = chrono::steady_clock::now();

        // Find how much time passed since last loop
        // 计算距离上一次循环过去了多少时间
        chrono::duration<double> elapsed = currentTime - lastTime;
        lastTime = currentTime;

        // Update the traffic light system
        // 更新交通灯系统
        controller.update(elapsed.count());

        // Only print when the phase changes
        // 只有阶段改变时才打印
        if (controller.getCurrentPhase() != lastPrintedPhase) {
            lastPrintedPhase = controller.getCurrentPhase();
            printState(controller.getState());
        }

        // Sleep a little so the loop does not run too fast
        // 暂停一点时间，避免循环运行太快
        this_thread::sleep_for(chrono::milliseconds(50));
    }

    return 0;
}
